### ISSUE TITLE
Intertemporal Asset Pricing using scipy.optimize.broyden1

### ISSUE THREAD

**Issue by danielkdimitrov** [OpenSourceEcon/BootCamp2019#39]
scipy.optimize.broyden1 requires a parameter alpha representing the Jacobian of the function. What would be a good guess for it considering the asset pricing equations (5) and (7) from the script?

**Comment by rebekahanne** [comment]
@danielkdimitrov: I don't think alpha is actually a required parameter, and I was able to get a solution without using the Jacobian. I was able to use broyden1 just with an objective function and initial guess. Looking at the [documentation](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.broyden1.html), alpha is optional.

**Comment by danielkdimitrov** [comment]
@rebekahanne You're right. Thanks!
