### ISSUE TITLE
Gauss-Seidel

### ISSUE THREAD

**Issue by Xincheng-Qiu** [OpenSourceEcon/BootCamp2019#45]
I think there is a typo in equation (16.3) for the Gauss-Seidel method in IterativeSolvers.pdf. The x-values of the second term in the brackets should be from the (k+1)-th iteration. 
![image](https://user-images.githubusercontent.com/44378668/62407688-36b94c00-b582-11e9-83c9-b47ea6e2b864.png)
The current expression is actually the Jacobi method and so is equation (16.4) too.

**Comment by rickecon** [comment]
@Xincheng-Qiu . Equation (16.3) in the lab is written in exactly the same way as in Judd (1998, p. 72) equation (3.6.3). The only difference is in how the indices over which the terms are summed are expressed (but they are the same). Below is the specification in Judd (1998, p. 72) equation (3.6.3).

![GS](https://user-images.githubusercontent.com/4317690/62430152-e3f4a700-b6dd-11e9-89c1-0a3c16763372.png)

I think the equation above is the correct specification of the Gauss-Seidel algorithm. Or at least, your issue with the `k` superscript on the second term in the brackets is not the problem.

Judd (1998, p. 71) specifies the Gauss-Jacobi algorithm in equation (3.6.2).

![GJ](https://user-images.githubusercontent.com/4317690/62430086-1b168880-b6dd-11e9-8d86-5eb25559742d.png)

The reference for Judd (1998) is the following.

Kenneth L. Judd, *Numerical Methods in Economics*, MIT Press, 1998.

**Comment by Xincheng-Qiu** [comment]
@rickecon  I think Judd (1998, p. 72) equation (3.6.3) is the same as my specification above. Equation (16.3) in the lab (see below), however, specifies the (k+1)-th iteration term (mistakenly) as the k-th iteration term. 
![image](https://user-images.githubusercontent.com/44378668/62430224-3edace00-b6df-11e9-9837-b816978e8904.png)

**Comment by Xincheng-Qiu** [comment]
@rickecon Ah I guess I didn't express it clearly in my first post. The equation in my first post is the correct one, not the wrong expression in the lab file.
