### ISSUE TITLE
(Possible) minor error

### ISSUE THREAD

**Issue by keertanavc** [OpenSourceEcon/BootCamp2019#9]
Hi,

I was looking at the function isvalid in the box.py file. There's a checking condition for roll: 
`
 if roll not in range(2, 13):
`
Shouldn't the range be range (1, 13) considering that eventually a single dice could be rolled in which case 1 is a legit roll number?

**Comment by rickecon** [comment]
@keertanavc. No. This is not a typo or an error in `box.py`. The line `if roll not in range(2, 13):` has to do with the fact that you have already rolled a number. @rebekahanne

**Comment by keertanavc** [comment]
The PS mentions that "However, if the sum of the player’s remaining numbers is 6 or less, role only one die." In the situation that my remaining numbers are, say, [1, 2] and I roll a single die and get a 1, isvalid(1, [1,2]) will return a False indicating that the roll is invalid whereas it is actually valid? So shouldn't the code be instead `if roll not in range(1, 13):` (if we want to squeeze in both the single and double roll cases into one check)? I might be missing something stupid!

**Comment by rebekahanne** [comment]
I think there are many ways to implement the methods needed to solve this problem. If the isvalid check is only being used for a double roll, then range(2, 13) should be fine. However, as @keertanavc mentions, if the player's sum is less than 6, then only one dice will be rolled. Here, the range(1,7) would be appropriate.
